const brands = [
	{ name: 'Acura', marka_id: 1 },
	{ name: 'Alfa-Romeo', marka_id: 2 },
	{ name: 'Aston martin', marka_id: 3 },
	{ name: 'Audi', marka_id: 4 },
	{ name: 'BAIC', marka_id: 5 },
	{ name: 'Bentley', marka_id: 6 },
	{ name: 'BMW', marka_id: 7 },
	{ name: 'Cadillac', marka_id: 8 },
	{ name: 'Chevrolet', marka_id: 9 },
	{ name: 'Chevrolet (Korea)', marka_id: 10 },
	{ name: 'Chrysler', marka_id: 11 },
	{ name: 'Citroen', marka_id: 12 },
	{ name: 'Daihatsu', marka_id: 13 },
	{ name: 'DFSK', marka_id: 14 },
	{ name: 'Dodge', marka_id: 15 },
	{ name: 'ETC', marka_id: 16 },
	{ name: 'Ferrari', marka_id: 17 },
	{ name: 'Fiat', marka_id: 18 },
	{ name: 'Ford', marka_id: 19 },
	{ name: 'Genesis', marka_id: 20 },
	{ name: 'GMC', marka_id: 21 },
	{ name: 'Honda', marka_id: 22 },
	{ name: 'Hummer', marka_id: 23 },
	{ name: 'Hyundai', marka_id: 24 },
	{ name: 'Infiniti', marka_id: 25 },
	{ name: 'Jaguar', marka_id: 26 },
	{ name: 'Jeep', marka_id: 27 },
	{ name: 'SsangYong', marka_id: 28 },
	{ name: 'KIA', marka_id: 29 },
	{ name: 'Lamborghini', marka_id: 30 },
	{ name: 'Land Rover', marka_id: 31 },
	{ name: 'Lexus', marka_id: 32 },
	{ name: 'Lincoln', marka_id: 33 },
	{ name: 'Lotus', marka_id: 34 },
	{ name: 'Maserati', marka_id: 35 },
	{ name: 'Maybach', marka_id: 36 },
	{ name: 'Mazda', marka_id: 37 },
	{ name: 'McLaren', marka_id: 38 },
	{ name: 'Mercedes-Benz', marka_id: 39 },
	{ name: 'Mercury', marka_id: 40 },
	{ name: 'Mini', marka_id: 41 },
	{ name: 'Mitsubishi', marka_id: 42 },
	{ name: 'Mitsuoka', marka_id: 43 },
	{ name: 'Nissan', marka_id: 44 },
	{ name: 'Others', marka_id: 45 },
	{ name: 'Peugeot', marka_id: 46 },
	{ name: 'Polestar', marka_id: 47 },
	{ name: 'Porsche', marka_id: 48 },
	{ name: 'Renault-Korea (Samsung)', marka_id: 49 },
	{ name: 'Rolls-Royce', marka_id: 50 },
	{ name: 'Saab', marka_id: 51 },
	{ name: 'Scion', marka_id: 52 },
	{ name: 'Smart', marka_id: 53 },
	{ name: 'Subaru', marka_id: 54 },
	{ name: 'Suzuki', marka_id: 55 },
	{ name: 'Tesla', marka_id: 56 },
	{ name: 'Toyota', marka_id: 57 },
	{ name: 'Volkswagen', marka_id: 58 },
	{ name: 'Volvo', marka_id: 59 },
]

export default brands
