const models = [
	{
		marka_id: 1,
		models: [{ model_id: 'MDX' }, { model_id: 'TL' }, { model_id: 'TSX' }],
	},
	{
		marka_id: 2,
		models: [{ model_id: '4C' }, { model_id: 'Brera' }],
	},
	{
		marka_id: 3,
		models: [
			{ model_id: 'DB11' },
			{ model_id: 'DB9' },
			{ model_id: 'DBS' },
			{ model_id: 'DBX' },
			{ model_id: 'Rapide' },
			{ model_id: 'Vanquish' },
			{ model_id: 'Vantage' },
		],
	},
	{
		marka_id: 4,
		models: [
			{ model_id: 'A1' },
			{ model_id: 'A3' },
			{ model_id: 'A4' },
			{ model_id: 'A5' },
			{ model_id: 'A6' },
			{ model_id: 'A7' },
			{ model_id: 'A8' },
			{ model_id: 'Allroad Quattro' },
			{ model_id: 'e-tron' },
			{ model_id: 'e-tron GT' },
			{ model_id: 'Q2' },
			{ model_id: 'Q3' },
			{ model_id: 'Q4 e-tron' },
			{ model_id: 'Q5' },
			{ model_id: 'Q7' },
			{ model_id: 'Q8' },
			{ model_id: 'Q8 e-tron' },
			{ model_id: 'R8' },
			{ model_id: 'RS e-tron GT' },
			{ model_id: 'RS3' },
			{ model_id: 'RS5' },
			{ model_id: 'RS6' },
			{ model_id: 'RS7' },
			{ model_id: 'RSQ8' },
			{ model_id: 'S3' },
			{ model_id: 'S4' },
			{ model_id: 'S5' },
			{ model_id: 'S6' },
			{ model_id: 'S7' },
			{ model_id: 'S8' },
			{ model_id: 'SQ5' },
			{ model_id: 'SQ8' },
			{ model_id: 'TT' },
			{ model_id: 'TTRS' },
			{ model_id: 'TTS' },
		],
	},
	{
		marka_id: 5,
		models: [{ model_id: 'CK MINI Truck' }, { model_id: 'CK Mini Van' }],
	},
	{
		marka_id: 6,
		models: [
			{ model_id: 'Bentayga' },
			{ model_id: 'Brooklands' },
			{ model_id: 'Continental' },
			{ model_id: 'Flying Spur' },
			{ model_id: 'Mulsanne' },
		],
	},
	{
		marka_id: 7,
		models: [
			{ model_id: '1-Series' },
			{ model_id: '1M' },
			{ model_id: '2-Series' },
			{ model_id: '3-Series' },
			{ model_id: '4-Series' },
			{ model_id: '5-Series' },
			{ model_id: '6-Series' },
			{ model_id: '7-Series' },
			{ model_id: '8-Series' },
			{ model_id: 'Gran Turismo' },
			{ model_id: 'i3' },
			{ model_id: 'i4' },
			{ model_id: 'i5' },
			{ model_id: 'i7' },
			{ model_id: 'i8' },
			{ model_id: 'iX' },
			{ model_id: 'iX1' },
			{ model_id: 'iX3' },
			{ model_id: 'M Coupe/Roadster' },
			{ model_id: 'M2' },
			{ model_id: 'M3' },
			{ model_id: 'M4' },
			{ model_id: 'M5' },
			{ model_id: 'M6' },
			{ model_id: 'M8' },
			{ model_id: 'X1' },
			{ model_id: 'X2 (F39)' },
			{ model_id: 'X3' },
			{ model_id: 'X3M' },
			{ model_id: 'X4' },
			{ model_id: 'X4M' },
			{ model_id: 'X5' },
			{ model_id: 'X5M' },
			{ model_id: 'X6' },
			{ model_id: 'X6M' },
			{ model_id: 'X7' },
			{ model_id: 'XM' },
			{ model_id: 'Z3' },
			{ model_id: 'Z4' },
			{ model_id: 'Z8' },
		],
	},
	{
		marka_id: 8,
		models: [
			{ model_id: 'ATS' },
			{ model_id: 'Concour' },
			{ model_id: 'CT4' },
			{ model_id: 'CT5' },
			{ model_id: 'CT5-V' },
			{ model_id: 'CT6' },
			{ model_id: 'CTS' },
			{ model_id: 'CTS-V' },
			{ model_id: 'DTS' },
			{ model_id: 'Escalade' },
			{ model_id: 'Fleetwood' },
			{ model_id: 'SeVille' },
			{ model_id: 'SRX' },
			{ model_id: 'STS' },
			{ model_id: 'XT4' },
			{ model_id: 'XT5' },
			{ model_id: 'XT6' },
		],
	},
	{
		marka_id: 9,
		models: [
			{ model_id: 'Astro Van' },
			{ model_id: 'Blazer' },
			{ model_id: 'Camaro' },
			{ model_id: 'Chevy Van' },
			{ model_id: 'Corvette' },
			{ model_id: 'Express Van' },
			{ model_id: 'Others' },
			{ model_id: 'Silverado' },
			{ model_id: 'Surburban' },
			{ model_id: 'Tahoe' },
			{ model_id: 'Tracker' },
		],
	},
	{
		marka_id: 10,
		models: [
			{ model_id: 'Acadia' },
			{ model_id: 'Alpheon' },
			{ model_id: 'Aveo' },
			{ model_id: 'Bolt EV' },
			{ model_id: 'Camaro' },
			{ model_id: 'Captiva' },
			{ model_id: 'Colorado' },
			{ model_id: 'Corvette' },
			{ model_id: 'Cruze' },
			{ model_id: 'Damas' },
			{ model_id: 'Equinox' },
			{ model_id: 'Espero' },
			{ model_id: 'G2X' },
			{ model_id: 'Gentra' },
			{ model_id: 'Impala' },
			{ model_id: 'Kalos' },
			{ model_id: 'Labo' },
			{ model_id: 'Lacetti' },
			{ model_id: 'Lanos' },
			{ model_id: 'Lemans' },
			{ model_id: 'Magnus' },
			{ model_id: 'Malibu' },
			{ model_id: 'Matiz' },
			{ model_id: 'Orlando' },
			{ model_id: 'Prince' },
			{ model_id: 'Rezzo' },
			{ model_id: 'Spark' },
			{ model_id: 'Statesman' },
			{ model_id: 'Super Salon' },
			{ model_id: 'Tahoe' },
			{ model_id: 'Tico' },
			{ model_id: 'Tosca' },
			{ model_id: 'Trailblazer' },
			{ model_id: 'Traverse' },
			{ model_id: 'Trax' },
			{ model_id: 'VERITAS' },
			{ model_id: 'VOLT' },
			{ model_id: 'Winstorm' },
			{ model_id: '볼트 EUV' },
		],
	},
	{
		marka_id: 11,
		models: [
			{ model_id: '200' },
			{ model_id: '300C' },
			{ model_id: 'Crossfire' },
			{ model_id: 'Grand Voyager' },
			{ model_id: 'Pacifica' },
			{ model_id: 'Prowler' },
			{ model_id: 'PT Cruiser' },
			{ model_id: 'Sebring' },
		],
	},
	{
		marka_id: 12,
		models: [
			{ model_id: 'C3 Aircross' },
			{ model_id: 'C4 Cactus' },
			{ model_id: 'C4 Picasso' },
			{ model_id: 'C4 SpaceTourer' },
			{ model_id: 'C5 Aircross' },
			{ model_id: 'DS3' },
			{ model_id: 'DS4' },
			{ model_id: 'DS5' },
			{ model_id: 'DS7' },
		],
	},
	{
		marka_id: 13,
		models: [
			{ model_id: 'Copen' },
			{ model_id: 'Materia' },
			{ model_id: 'Wake' },
		],
	},
	{
		marka_id: 14,
		models: [
			{ model_id: 'C31' },
			{ model_id: 'C35' },
			{ model_id: 'Fengon ix5' },
			{ model_id: 'SX6' },
		],
	},
	{
		marka_id: 17,
		models: [
			{ model_id: '296' },
			{ model_id: '458' },
			{ model_id: '488' },
			{ model_id: '575M' },
			{ model_id: '599' },
			{ model_id: '612' },
			{ model_id: '812' },
			{ model_id: 'California' },
			{ model_id: 'F12 Berlinetta' },
			{ model_id: 'F355' },
			{ model_id: 'F430' },
			{ model_id: 'F8' },
			{ model_id: 'FF' },
			{ model_id: 'GTC4 Lusso' },
			{ model_id: 'Portofino' },
			{ model_id: 'Purosangue' },
			{ model_id: 'Roma' },
			{ model_id: 'SF90' },
		],
	},
	{
		marka_id: 18,
		models: [
			{ model_id: '500' },
			{ model_id: '500X' },
			{ model_id: 'Ducato' },
			{ model_id: 'Feelmont' },
			{ model_id: 'Others' },
		],
	},
	{
		marka_id: 19,
		models: [
			{ model_id: 'Bronco' },
			{ model_id: 'E-Series' },
			{ model_id: 'Escape' },
			{ model_id: 'Expedition' },
			{ model_id: 'Explorer' },
			{ model_id: 'F150' },
			{ model_id: 'F250' },
			{ model_id: 'F350' },
			{ model_id: 'Five Hundred' },
			{ model_id: 'Focus' },
			{ model_id: 'Freestyle' },
			{ model_id: 'Fusion' },
			{ model_id: 'Kuga' },
			{ model_id: 'Mondeo' },
			{ model_id: 'Mustang' },
			{ model_id: 'Others' },
			{ model_id: 'Ranger' },
			{ model_id: 'Taurus' },
			{ model_id: 'Transit' },
		],
	},
	{
		marka_id: 20,
		models: [
			{ model_id: 'EQ900' },
			{ model_id: 'G70' },
			{ model_id: 'G80' },
			{ model_id: 'G90' },
			{ model_id: 'GV60' },
			{ model_id: 'GV70' },
			{ model_id: 'GV80' },
		],
	},
	{
		marka_id: 21,
		models: [
			{ model_id: 'Canyon' },
			{ model_id: 'Hummer EV' },
			{ model_id: 'Safari' },
			{ model_id: 'Savana' },
			{ model_id: 'Sierra' },
			{ model_id: 'Terrain' },
			{ model_id: 'Yukon' },
		],
	},
	{
		marka_id: 22,
		models: [
			{ model_id: 'Accord' },
			{ model_id: 'Civic' },
			{ model_id: 'CR-V' },
			{ model_id: 'CR-Z' },
			{ model_id: 'Crosstour' },
			{ model_id: 'Element' },
			{ model_id: 'HR-V' },
			{ model_id: 'Legend' },
			{ model_id: 'N-ONE' },
			{ model_id: 'Odyssey' },
			{ model_id: 'Pilot' },
			{ model_id: 'S2000' },
			{ model_id: 'S660' },
		],
	},
	{
		marka_id: 23,
		models: [{ model_id: 'H1' }, { model_id: 'H2' }, { model_id: 'H3' }],
	},
	{
		marka_id: 24,
		models: [
			{ model_id: 'Accent' },
			{ model_id: 'Aslan' },
			{ model_id: 'Atoz' },
			{ model_id: 'AVANTE' },
			{ model_id: 'Casper' },
			{ model_id: 'Click' },
			{ model_id: 'Dynasty' },
			{ model_id: 'Elantra' },
			{ model_id: 'Equus' },
			{ model_id: 'Excel' },
			{ model_id: 'Galloper' },
			{ model_id: 'Genesis' },
			{ model_id: 'Grace' },
			{ model_id: 'Grandeur' },
			{ model_id: 'i30' },
			{ model_id: 'i40' },
			{ model_id: 'Ioniq' },
			{ model_id: 'Ioniq5' },
			{ model_id: 'Ioniq6' },
			{ model_id: 'Kona' },
			{ model_id: 'Lavita' },
			{ model_id: 'Marcia' },
			{ model_id: 'Maxcruz' },
			{ model_id: 'Nexo' },
			{ model_id: 'Palisade' },
			{ model_id: 'Pony' },
			{ model_id: 'Santafe' },
			{ model_id: 'Santamo' },
			{ model_id: 'Solati' },
			{ model_id: 'Sonata' },
			{ model_id: 'ST1' },
			{ model_id: 'Starex' },
			{ model_id: 'Staria' },
			{ model_id: 'Stella' },
			{ model_id: 'Terracan' },
			{ model_id: 'Tiburon' },
			{ model_id: 'Traget XG' },
			{ model_id: 'Tucson' },
			{ model_id: 'Tuscani' },
			{ model_id: 'Veloster' },
			{ model_id: 'Venue' },
			{ model_id: 'Veracruz' },
			{ model_id: 'Verna' },
		],
	},
	{
		marka_id: 25,
		models: [
			{ model_id: 'EX' },
			{ model_id: 'FX' },
			{ model_id: 'G' },
			{ model_id: 'JX' },
			{ model_id: 'M' },
			{ model_id: 'Q30' },
			{ model_id: 'Q50' },
			{ model_id: 'Q60' },
			{ model_id: 'Q70' },
			{ model_id: 'QX' },
			{ model_id: 'QX30' },
			{ model_id: 'QX50' },
			{ model_id: 'QX60' },
			{ model_id: 'QX70' },
			{ model_id: 'QX80' },
		],
	},
	{
		marka_id: 26,
		models: [
			{ model_id: 'Daimler' },
			{ model_id: 'E-PACE' },
			{ model_id: 'F-PACE' },
			{ model_id: 'F-TYPE' },
			{ model_id: 'I-PACE' },
			{ model_id: 'Others' },
			{ model_id: 'S-TYPE' },
			{ model_id: 'X-TYPE' },
			{ model_id: 'XE' },
			{ model_id: 'XF' },
			{ model_id: 'XJ' },
			{ model_id: 'XJ-6' },
			{ model_id: 'XJ-8' },
			{ model_id: 'XK' },
			{ model_id: 'XK8' },
			{ model_id: 'XKR' },
		],
	},
	{
		marka_id: 27,
		models: [
			{ model_id: 'Cherokee' },
			{ model_id: 'Commander' },
			{ model_id: 'Compass' },
			{ model_id: 'Gladiator' },
			{ model_id: 'Renegade' },
			{ model_id: 'Wrangler' },
		],
	},
	{
		marka_id: 28,
		models: [
			{ model_id: 'Actyon' },
			{ model_id: 'Chairman' },
			{ model_id: 'KORANDO' },
			{ model_id: 'Kyron' },
			{ model_id: 'Musso' },
			{ model_id: 'Rexton' },
			{ model_id: 'Rodius' },
			{ model_id: 'TIBOLI' },
			{ model_id: 'Torres' },
		],
	},
	{
		marka_id: 29,
		models: [
			{ model_id: 'Avella' },
			{ model_id: 'Bongo III Minibus' },
			{ model_id: 'Canival' },
			{ model_id: 'Capital' },
			{ model_id: 'Carens' },
			{ model_id: 'Cerato' },
			{ model_id: 'Concorde' },
			{ model_id: 'Credos' },
			{ model_id: 'Elan' },
			{ model_id: 'Enterprise' },
			{ model_id: 'EV3' },
			{ model_id: 'EV6' },
			{ model_id: 'EV9' },
			{ model_id: 'K3' },
			{ model_id: 'K5' },
			{ model_id: 'K7' },
			{ model_id: 'K8' },
			{ model_id: 'K9' },
			{ model_id: 'LOTZE' },
			{ model_id: 'Mohave' },
			{ model_id: 'Morning' },
			{ model_id: 'Niro' },
			{ model_id: 'OPIRUS' },
			{ model_id: 'Optima' },
			{ model_id: 'Parktown' },
			{ model_id: 'Porte' },
			{ model_id: 'Potentia' },
			{ model_id: 'Pride' },
			{ model_id: 'RAY' },
			{ model_id: 'Regal' },
			{ model_id: 'Seltos' },
			{ model_id: 'Sephia' },
			{ model_id: 'Sorento' },
			{ model_id: 'Soul' },
			{ model_id: 'Spectra' },
			{ model_id: 'Sportage' },
			{ model_id: 'Stinger' },
			{ model_id: 'Stonic' },
			{ model_id: 'Visto' },
		],
	},
]

export default models
